[package]
name = "gltr"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.210"
serde_json = "1.0.128"
serde_derive = "1.0.210"
base64 = "0.22.1"
rand = "0.8.5"


[profile.test]
inherits="release"
